const StripedSeparator: React.FC = () => {
  return (
    <div className="flex flex-col">
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
      <div className="bg-white/20 w-full h-2"></div>
      <div className="w-full h-2"></div>
    </div>
  );
};

export default StripedSeparator;
